version: '3.9'
services:
  db:
    image: postgres:13
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transcDB
    networks:
      - transcendence

networks:
  transcendence: