version: '3.9'
services:
  ##############
  ## POSTGRES ##
  postgres_db:
    image: postgres:15
    networks:
      - database
    environment:
      - PGUSER=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=postgres_dbw
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: postgres_db
  ##############
  ## SERVER ##
  server:
    build:
      context: ./server
    networks:
      - webapp
      - database
    ports:
      - 5500:5500
# for coding purposes, might delete later
      - 3003:3003
# for prisma studio (visualizing database), might delete later
      - 5555:5555
      - 3007:3007
    environment:
      - SECRET="¯\_(ツ)_/¯"
    volumes:
      - ./server/src:/app/server/src
      - ./server/uploads:/app/server/uploads
      - ./server/prisma:/app/server/prisma
    depends_on:
      - postgres_db
    restart: always
    command: ['./wait-for-it.sh', 'postgres_db:5432', '--', 'nodemon']
    container_name: server
  #############
  ## CLIENT ##
  client:
    build:
      context: ./client
    env_file:
      - ./client/.env
    volumes:
      # - ./client/node_modules:/app/node_modules
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    networks:
      - webapp
    ports:
      - 3000:3000
    command: npm start
    stdin_open: true
    restart: always
    container_name: client

networks:
  webapp:
    driver: bridge
  database:
    driver: bridge
  web:
    driver: bridge

volumes:
  postgres-data: