version: '3.0'

services:
	nest:
		container_name: nest
		build:
			context: ./backend
		env_file: ./backend/.env
		depends_on: 
			- backend_database

	postgres:
		container_name:	backend_database
		image: postgres
		env_file: .env
		ports: 
			- 5432:5432
		# volumes:
		# - postgres-data:/var/lib/postgresql/data