version: '3.9'

services:
  backend_database:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: backend_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # networks:
    #   - backend_network

volumes:
  postgres-data: